package com.uit.entity;
// Generated Jun 16, 2021 9:11:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name="BOOK"
    ,schema="DOAN_NEW"
)
public class Book  implements java.io.Serializable {


     private long bookId;
     private Category category;
     private String title;
     private String author;
     private String description;
     private String isbn;
     private String image;
     private Double price;
     private Date publishDate;
     private Date lastUpdate;
     private Long curQuantity;
     private String status;
     private Set<InventoryTracking> inventoryTrackings = new HashSet<InventoryTracking>(0);
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public Book() {
    }

	
    public Book(long bookId, Category category, Date lastUpdate) {
        this.bookId = bookId;
        this.category = category;
        this.lastUpdate = lastUpdate;
    }
    public Book(long bookId, Category category, String title, String author, String description, String isbn, String image, Double price, Date publishDate, Date lastUpdate, Long curQuantity, String status, Set<InventoryTracking> inventoryTrackings, Set<Review> reviews, Set<OrderDetail> orderDetails) {
       this.bookId = bookId;
       this.category = category;
       this.title = title;
       this.author = author;
       this.description = description;
       this.isbn = isbn;
       this.image = image;
       this.price = price;
       this.publishDate = publishDate;
       this.lastUpdate = lastUpdate;
       this.curQuantity = curQuantity;
       this.status = status;
       this.inventoryTrackings = inventoryTrackings;
       this.reviews = reviews;
       this.orderDetails = orderDetails;
    }
   
     @Id 
     
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "book_generator")
    @SequenceGenerator(name="book_generator", sequenceName = "seq_book", allocationSize = 1)
    @Column(name="BOOK_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getBookId() {
        return this.bookId;
    }
    
    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATEGORY_ID", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="TITLE", length=128)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="AUTHOR", length=64)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ISBN", length=15)
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    
    @Column(name="IMAGE", length=100)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="PRICE", precision=126, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PUBLISH_DATE", length=7)
    public Date getPublishDate() {
        return this.publishDate;
    }
    
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_UPDATE", nullable=false, length=7)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    
    @Column(name="CUR_QUANTITY", precision=10, scale=0)
    public Long getCurQuantity() {
        return this.curQuantity;
    }
    
    public void setCurQuantity(Long curQuantity) {
        this.curQuantity = curQuantity;
    }

    
    @Column(name="STATUS", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="book", cascade = CascadeType.ALL)
    public Set<InventoryTracking> getInventoryTrackings() {
        return this.inventoryTrackings;
    }
    
    public void setInventoryTrackings(Set<InventoryTracking> inventoryTrackings) {
        this.inventoryTrackings = inventoryTrackings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="book")
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="book")
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }
    
    public void addInventory(InventoryTracking inventoryTracking){
        this.inventoryTrackings.add(inventoryTracking);
    }

}


