package com.uit.entity;
// Generated May 24, 2021 9:48:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookOrder generated by hbm2java
 */
@Entity
@Table(name="BOOK_ORDER"
    ,schema="DOAN_NEW"
)
public class BookOrder  implements java.io.Serializable {


     private long orderId;
     private Customer customer;
     private Date orderDate;
     private String shippingAddress;
     private String recipentName;
     private String recipentPhone;
     private String paymentMethod;
     private Double total;
     private String status;
     private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public BookOrder() {
    }


    public BookOrder(long orderId, Customer customer, Date orderDate) {
        this.orderId = orderId;
        this.customer = customer;
        this.orderDate = orderDate;
    }
    public BookOrder(Customer customer, Date orderDate, String shippingAddress, String recipentName, String recipentPhone, String paymentMethod, Double total, String status) {
       this.customer = customer;
       this.orderDate = orderDate;
       this.shippingAddress = shippingAddress;
       this.recipentName = recipentName;
       this.recipentPhone = recipentPhone;
       this.paymentMethod = paymentMethod;
       this.total = total;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="ORDER_ID", unique=true, nullable=false, precision=10, scale=0)
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "order_generator")
    @SequenceGenerator(name="order_generator", sequenceName = "seq_book_order", allocationSize = 1)
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ORDER_DATE", nullable=false, length=7)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="SHIPPING_ADDRESS", length=256)
    public String getShippingAddress() {
        return this.shippingAddress;
    }
    
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    
    @Column(name="RECIPENT_NAME", length=30)
    public String getRecipentName() {
        return this.recipentName;
    }
    
    public void setRecipentName(String recipentName) {
        this.recipentName = recipentName;
    }

    
    @Column(name="RECIPENT_PHONE", length=15)
    public String getRecipentPhone() {
        return this.recipentPhone;
    }
    
    public void setRecipentPhone(String recipentPhone) {
        this.recipentPhone = recipentPhone;
    }

    
    @Column(name="PAYMENT_METHOD", length=20)
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    
    @Column(name="TOTAL", precision=126, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }

    
    @Column(name="STATUS", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bookOrder", cascade = CascadeType.ALL)
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }

    public void addOrderDetail(OrderDetail orderDetail){
        this.orderDetails.add(orderDetail);
    }


}


