package com.uit.entity;
// Generated May 24, 2021 9:48:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="CATEGORY"
    ,schema="DOAN_NEW"
)
public class Category  implements java.io.Serializable {


     private long categoryId;
     private String name;
     private Set<Book> books = new HashSet<Book>(0);

    public Category() {
    }

	
    public Category(long categoryId) {
        this.categoryId = categoryId;
    }
    public Category(long categoryId, String name, Set<Book> books) {
       this.categoryId = categoryId;
       this.name = name;
       this.books = books;
    }
   
     @Id 

    
    @Column(name="CATEGORY_ID", unique=true, nullable=false, precision=10, scale=0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "category_generator")
    @SequenceGenerator(name="category_generator", sequenceName = "seq_category", allocationSize = 1)
    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="NAME", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }

    @Override
    public String toString() {
        return name;
    }




}


