package com.uit.entity;
// Generated Jun 16, 2021 9:11:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InventoryTracking generated by hbm2java
 */
@Entity
@Table(name="INVENTORY_TRACKING"
    ,schema="DOAN_NEW"
)
public class InventoryTracking  implements java.io.Serializable {


     private long trackingId;
     private Book book;
     private Supplier supplier;
     private Long quantity;
     private Double subtotal;
     private Date receiptDate;

    public InventoryTracking() {
    }

	
    public InventoryTracking(long trackingId, Date receiptDate) {
        this.trackingId = trackingId;
        this.receiptDate = receiptDate;
    }
    public InventoryTracking(long trackingId, Book book, Supplier supplier, Long quantity, Double subtotal, Date receiptDate) {
       this.trackingId = trackingId;
       this.book = book;
       this.supplier = supplier;
       this.quantity = quantity;
       this.subtotal = subtotal;
       this.receiptDate = receiptDate;
    }
   
     @Id 

    
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "inventory_generator")
    @SequenceGenerator(name="inventory_generator", sequenceName = "seq_inventory", allocationSize = 1)
    @Column(name="TRACKING_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getTrackingId() {
        return this.trackingId;
    }
    
    public void setTrackingId(long trackingId) {
        this.trackingId = trackingId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BOOK_ID")
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SUPPLIER_ID")
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    
    @Column(name="QUANTITY", precision=10, scale=0)
    public Long getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="SUBTOTAL", precision=126, scale=0)
    public Double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECEIPT_DATE", nullable=false, length=7)
    public Date getReceiptDate() {
        return this.receiptDate;
    }
    
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }




}


