package com.uit.entity;
// Generated May 24, 2021 9:48:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId  implements java.io.Serializable {


     private long orderId;
     private long bookId;

    public OrderDetailId() {
    }

    public OrderDetailId(long orderId, long bookId) {
       this.orderId = orderId;
       this.bookId = bookId;
    }
   


    @Column(name="ORDER_ID", nullable=false, precision=10, scale=0)
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }


    @Column(name="BOOK_ID", nullable=false, precision=10, scale=0)
    public long getBookId() {
        return this.bookId;
    }
    
    public void setBookId(long bookId) {
        this.bookId = bookId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderDetailId) ) return false;
		 OrderDetailId castOther = ( OrderDetailId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getBookId()==castOther.getBookId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getOrderId();
         result = 37 * result + (int) this.getBookId();
         return result;
   }   


}


