package com.uit.entity;
// Generated May 24, 2021 9:48:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name="REVIEW"
    ,schema="DOAN_NEW"
)
public class Review  implements java.io.Serializable {


     private long reviewId;
     private Customer customer;
     private long rating;
     private String headline;
     private String comment;
     private Date reviewTime;

    public Review() {
    }

	
    public Review(long reviewId, Customer customer, long rating, Date reviewTime) {
        this.reviewId = reviewId;
        this.customer = customer;
        this.rating = rating;
        this.reviewTime = reviewTime;
    }
    public Review(long reviewId, Customer customer, long rating, String headline, String comment, Date reviewTime) {
       this.reviewId = reviewId;
       this.customer = customer;
       this.rating = rating;
       this.headline = headline;
       this.comment = comment;
       this.reviewTime = reviewTime;
    }
   
     @Id 

    
    @Column(name="REVIEW_ID", unique=true, nullable=false, precision=10, scale=0)
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "review_generator")
    @SequenceGenerator(name="review_generator", sequenceName = "seq_review", allocationSize = 1)
    public long getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(long reviewId) {
        this.reviewId = reviewId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    
    @Column(name="RATING", nullable=false, precision=10, scale=0)
    public long getRating() {
        return this.rating;
    }
    
    public void setRating(long rating) {
        this.rating = rating;
    }

    
    @Column(name="HEADLINE", length=128)
    public String getHeadline() {
        return this.headline;
    }
    
    public void setHeadline(String headline) {
        this.headline = headline;
    }

    
    @Column(name="COMMENT", length=500)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REVIEW_TIME", nullable=false, length=7)
    public Date getReviewTime() {
        return this.reviewTime;
    }
    
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }




}


