package com.uit.entity;
// Generated Jun 16, 2021 9:11:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="SUPPLIER"
    ,schema="DOAN_NEW"
)
public class Supplier  implements java.io.Serializable {


     private long supplierId;
     private String name;
     private String address;
     private String phone;
     private Set<InventoryTracking> inventoryTrackings = new HashSet<InventoryTracking>(0);

    public Supplier() {
    }

	
    public Supplier(long supplierId) {
        this.supplierId = supplierId;
    }
    public Supplier(long supplierId, String name, String address, String phone, Set<InventoryTracking> inventoryTrackings) {
       this.supplierId = supplierId;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.inventoryTrackings = inventoryTrackings;
    }
   
     @Id 

    
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "supplier_generator")
    @SequenceGenerator(name="supplier_generator", sequenceName = "seq_supplier", allocationSize = 1)
    @Column(name="SUPPLIER_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(long supplierId) {
        this.supplierId = supplierId;
    }

    
    @Column(name="NAME", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ADDRESS", length=64)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="PHONE", length=15)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<InventoryTracking> getInventoryTrackings() {
        return this.inventoryTrackings;
    }
    
    public void setInventoryTrackings(Set<InventoryTracking> inventoryTrackings) {
        this.inventoryTrackings = inventoryTrackings;
    }

    @Override
    public String toString() {
        return name;
    }

}


