package com.uit.entity;
// Generated Jun 16, 2021 9:11:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usr generated by hbm2java
 */
@Entity
@Table(name="USR"
    ,schema="DOAN_NEW"
    , uniqueConstraints = @UniqueConstraint(columnNames="EMAIL") 
)
public class Usr  implements java.io.Serializable {


     private long usrId;
     private String email;
     private String password;
     private String fullName;

    public Usr() {
    }

	
    public Usr(long usrId) {
        this.usrId = usrId;
    }
    public Usr(long usrId, String email, String password, String fullName) {
       this.usrId = usrId;
       this.email = email;
       this.password = password;
       this.fullName = fullName;
    }
   
     @Id 

    
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_generator")
    @SequenceGenerator(name="user_generator", sequenceName = "seq_usr", allocationSize = 1)
    @Column(name="USR_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getUsrId() {
        return this.usrId;
    }
    
    public void setUsrId(long usrId) {
        this.usrId = usrId;
    }

    
    @Column(name="EMAIL", unique=true, length=30)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PASSWORD", length=16)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="FULL_NAME", length=30)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }




}


